name: Terraform Apply

on:
  push:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

permissions:
  actions: read
  contents: read

jobs:
  terraform-apply:
    if: ${{false}}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./environments/production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Download plan
        uses: dawidd6/action-download-artifact@v9
        with:
          path: ./environments/production
          workflow: plan.yml
          pr: ${{github.event.pull_request.number}}

      - name: Move tfplan to cwd
        run: mv ./terraform-plan/tfplan ./tfplan

      - name: Apply plan
        run: terraform apply -input=false -auto-approve -no-color tfplan
